[package]
name = "wvr-data"
version = "0.1.2"
authors = ["gurke.club <contact@gurke.club>"]
edition = "2018"

[dependencies]
serde = "1.0"
serde_derive = "1.0"
anyhow = "1.0"
ron = "0.6"
directories-next = "2.0"
clap = "*"
